version: "3.9"

services:
  backend:
    build: ./queueHandler
    container_name: queuehandler-backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=${REDIS_URL}
      # - MONGO_URI=${MONGO_URI}
      # - MANIM_API_URL=${MANIM_API_URL}
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  # Optional Celery worker
  worker:
    build: ./queueHandler
    container_name: queuehandler-worker
    command: celery -A src.worker worker --loglevel=info
    working_dir: /app
    environment:
      - REDIS_URL=${REDIS_URL}
      - PYTHONPATH=/app
      # - MONGO_URI=${MONGO_URI}
      # - MANIM_API_URL=${MANIM_API_URL}
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - backend
      - redis
      - manim 
    volumes:
      - manim_shared:/shared

  manim:
    build: ./manim
    container_name: manim-renderer
    command: python -u watcher.py  
    volumes:
      - manim_shared:/shared 
      - ./bucketkey.json:/app/keyfile.json:ro
      - ./Manim:/manim
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/keyfile.json

volumes:
  manim_shared:

